// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function POSTGo(arg1) {
  return window['go']['main']['App']['POSTGo'](arg1);
}

export function ShowFolderPicker(arg1) {
  return window['go']['main']['App']['ShowFolderPicker'](arg1);
}
