// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function POSTGo(arg1:string):Promise<string>;

export function ShowFolderPicker(arg1:string):Promise<string>;
